language: python
python: 2.7

matrix:
  include:
    - python: 3.6
      install:
        - pip3 install coala-bears --pre
      script:
        - coala --ci

    - python: 2.7
      install:
        - pip install -r requirements.txt
        - pip install pycodestyle
      script:
        - python manage.py migrate
        - python manage.py test
services:
  - postgresql
  - redis-server
  - celery

addons:
  postgresql: "9.5"

before_script:
  - pycodestyle --exclude=migrations,settings.py,lib,tests,tmp --max-line-length=100 .
  - psql -c "CREATE DATABASE scancode;" -U postgres

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/dd260d20442f274ff140
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
